# Generated by Django 4.0.1 on 2022-01-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_rename_pub_date_poem_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_death',
        ),
    ]
