# Generated by Django 4.0.1 on 2022-01-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0003_remove_author_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='poet',
        ),
    ]
