# Generated by Django 4.0.1 on 2022-01-24 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0004_remove_poem_poet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
