# Generated by Django 4.0.1 on 2022-01-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0006_remove_book_genre_remove_book_isbn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.AddField(
            model_name='author',
            name='author',
            field=models.CharField(default='Гуськов', max_length=25),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='poems_count',
            field=models.IntegerField(default=0),
        ),
    ]
