# Generated by Django 4.0.1 on 2022-01-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0007_remove_book_language_author_author_book_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='name_book',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='poem',
            name='book',
            field=models.ManyToManyField(help_text='Enter books, where ware this poem', to='poems.Book'),
        ),
    ]
