# Generated by Django 4.0.1 on 2022-03-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0008_book_name_book_poem_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='poem',
            options={'ordering': ['tytle']},
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
    ]
