# Generated by Django 4.0.1 on 2022-03-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0010_number_person_personnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnumber',
            name='number',
        ),
        migrations.RemoveField(
            model_name='personnumber',
            name='person',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='ISBN', help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13),
        ),
        migrations.AddField(
            model_name='book',
            name='title_2',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.DeleteModel(
            name='Number',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='PersonNumber',
        ),
    ]
