# Generated by Django 4.0.1 on 2022-03-29 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0011_remove_personnumber_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='title_2',
        ),
    ]
