# Generated by Django 4.0.1 on 2022-03-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0014_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='ISBN', help_text='17 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=17),
        ),
        migrations.AlterField(
            model_name='poem',
            name='tytle',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
