# Generated by Django 4.0.1 on 2022-03-29 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0015_alter_book_isbn_alter_poem_tytle'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poems.author'),
        ),
        migrations.AddField(
            model_name='poem',
            name='summary',
            field=models.TextField(default=' ', help_text='Enter a brief description', max_length=1000),
        ),
    ]
