# Generated by Django 4.0.1 on 2022-03-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0016_poem_author_poem_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(help_text='Enter a brief description', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='poem',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='poem',
            name='summary',
            field=models.TextField(help_text='Enter a brief description', max_length=1000, null=True),
        ),
    ]
