# Generated by Django 4.0.1 on 2022-03-31 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0017_alter_author_first_name_alter_book_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='middl_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a brief description', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='poem',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poems.author'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
