# Generated by Django 4.0.1 on 2022-04-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0019_rename_publication_date_book_public_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='poem_lang',
            field=models.CharField(default='укр.', max_length=4),
        ),
    ]
