# Generated by Django 4.0.1 on 2022-04-02 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0020_poem_poem_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='', upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='author',
            field=models.ForeignKey(blank=True, default='Анатолій Гуськов', null=True, on_delete=django.db.models.deletion.SET_NULL, to='poems.author'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Enter a poem description', max_length=1000),
        ),
    ]
