# Generated by Django 4.0.1 on 2022-04-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0021_book_image_alter_poem_author_alter_poem_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name']},
        ),
        migrations.AddField(
            model_name='author',
            name='city',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='poem',
            name='collage',
            field=models.ImageField(blank=True, default='', upload_to='collages/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
