# Generated by Django 4.0.1 on 2022-04-30 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0023_author_date_of_death_alter_genre_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='collage',
        ),
    ]
