# Generated by Django 4.0.1 on 2022-05-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0025_book_author_status_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
