# Generated by Django 4.0.1 on 2022-05-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0027_remove_author_author_alter_poem_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-public_date']},
        ),
        migrations.AddField(
            model_name='book',
            name='image_book',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='poem',
            name='image_poem',
            field=models.CharField(default='', max_length=200),
        ),
    ]
