# Generated by Django 4.0.1 on 2022-05-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0029_genre_image_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre_text_color',
            field=models.CharField(default='darkblue', max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_book',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='poem',
            name='image_poem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
