# Generated by Django 4.0.1 on 2022-05-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0030_genre_genre_text_color_alter_book_image_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_text_color',
            field=models.CharField(default='bwbw', max_length=30),
        ),
    ]
