# Generated by Django 4.0.1 on 2022-05-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0031_genre_image_name_alter_genre_genre_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='collage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='image_genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
