# Generated by Django 4.0.1 on 2022-05-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0032_genre_collage_alter_genre_image_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='collage',
        ),
        migrations.AddField(
            model_name='poem',
            name='collage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
